apiVersion: k8s.nginx.org/v1
kind: VirtualServerRoute
metadata:
  name: grafana-dashboard
  namespace: monitoring
spec:
  host: artie.grafana.com
  upstreams:
  - name: grafana 
    service: nginx-grafana
    port: 80
  subroutes:
  - path: / 
    action:
      pass: grafana