apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: grafana-vs
  namespace: monitoring
spec:
  host: grafana.ingress.demo
  tls:
    secret: ingress-demo
  routes:
  - path: /
    route: monitoring/grafana-dashboard